
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>
  host: <%= ENV.fetch("DB_HOST", "db") %>  # 👈 use the service name
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: my_typescript_app_development

test:
  <<: *default
  database: my_typescript_app_test

production:
  primary: &primary_production
    <<: *default
    database: my_typescript_app_production
  cache:
    <<: *primary_production
    database: my_typescript_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_typescript_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_typescript_app_production_cable
    migrations_paths: db/cable_migrate
